apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "50051"
  DB_HOST: "auth-db-service"
  DB_PORT: "3306"
  DB_NAME: "auth_db"
  LOG_LEVEL: "info"
  JWT_EXPIRES_IN: "24h"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3002"
  GRPC_PORT: "50052"
  DB_HOST: "catalog-db-service"
  DB_PORT: "3306"
  DB_NAME: "catalog_db"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "order_events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3003"
  DB_HOST: "orders-db-service"
  DB_PORT: "3306"
  DB_NAME: "orders_db"
  LOG_LEVEL: "info"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "order_events"
  CATALOG_GRPC_URL: "catalog-service:50052"
  AUTH_GRPC_URL: "auth-service:50051"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3004"
  DB_HOST: "delivery-db-service"
  DB_PORT: "3306"
  DB_NAME: "delivery_db"
  LOG_LEVEL: "info"
  ORDERS_SERVICE_URL: "http://orders-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "3005"
  LOG_LEVEL: "info"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM: "delivereats.sa.usac@gmail.com"
  SMTP_FROM_NAME: "DeliverEats"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: delivereats
data:
  NODE_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  FRONTEND_URL: "https://delivereats.example.com"
  AUTH_SERVICE_URL: "auth-service:50051"
  CATALOG_SERVICE_URL: "http://catalog-service:3002"
  ORDERS_SERVICE_URL: "http://orders-service:3003"
  DELIVERY_SERVICE_URL: "http://delivery-service:3004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: delivereats
data:
  VITE_API_URL: "https://api.delivereats.example.com/api"
