apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: practica9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: us-central1-docker.pkg.dev/saproject201807411/delivereats/p8-users-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3101"
            - name: DB_HOST
              value: users-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: users_db
            - name: EVENT_BUS_URL
              value: amqp://helpdesk:helpdesk123@rabbitmq:5672
            - name: EVENT_EXCHANGE
              value: helpdesk.events
            - name: EVENT_BUS_ENABLED
              value: "true"
          ports:
            - containerPort: 3101
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: practica9
spec:
  selector:
    app: users-service
  ports:
    - port: 80
      targetPort: 3101
