apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practica9-ingress
  namespace: practica9
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 3101
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 3101
          - path: /api/tickets
            pathType: Prefix
            backend:
              service:
                name: tickets-service
                port:
                  number: 3102
          - path: /api/assignments
            pathType: Prefix
            backend:
              service:
                name: assignments-service
                port:
                  number: 3103
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 3104
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
