apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: delivereats
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ChangeMeRoot2024!"
  MYSQL_USER: "delivereats_app"
  MYSQL_PASSWORD: "DeliverEatsAppPwd2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: delivereats
type: Opaque
stringData:
  JWT_SECRET: "delivereats-super-secret-key-2024-change-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: delivereats
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "delivereats"
  RABBITMQ_DEFAULT_PASS: "rabbitmq2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: delivereats
type: Opaque
stringData:
  SMTP_USER: "delivereats.sa.usac@gmail.com"
  SMTP_PASS: "ypvd_qwer_asdf_zxcv"
